
name: first workflow
on: push
jobs:
  first-job:
   runs-on: ubuntu-latest
   steps:
    - name: Hello Github Action
      run: echo "Hello, this new  world!"
    - name: Bye Github Action
      run: echo "Bye github action!"
    # - name: Fail Job
    #   run: Exit 1  
