name: Validate File
on: 
  push:
  workflow_dispatch:
jobs:
    validate-file:
     runs-on: ubuntu-latest
     steps:
        - name: get-repo-code
          uses: actions/checkout@v4
       
        - name: validate Html file
          uses: test -f index.html

        - name: validate js file
          uses: test -f script.html

 